#!/bin/bash

cat > ${WORKSPACE}/.cd/build.sh<<EOF
# Compatible With Jenkins
# Script For build
die() {
    echo -e "\033[1;31m>>> $@ \033[0m"
    exit 1
}

[ -z ${WORKSPACE} ]&&WORKSPACE="."
cd ${WORKSPACE}
npm-cli-login -u storehub -e developer@storehub.com -p "a[RF8zZy" -r https://npm-proxy.fury.io/byP2nuz4Las5rf72y98D/storehub/
npm config set registry https://npm-proxy.fury.io/byP2nuz4Las5rf72y98D/storehub/ && npm config set ca ""
npm install
bash ~/set_npm_config
EOF
