#!/bin/bash
[ -e ${WORKSPACE}/.cd ] || mkdir ${WORKSPACE}/.cd
cat > ${WORKSPACE}/.cd/build.sh<<EOF
npm-cli-login -u storehub -e developer@storehub.com -p "a[RF8zZy" -r https://npm-proxy.fury.io/byP2nuz4Las5rf72y98D/storehub/
npm config set registry https://npm-proxy.fury.io/byP2nuz4Las5rf72y98D/storehub/ && npm config set ca ""
yarn install
yarn build
bash ~/set_npm_config
EOF

cat>${WORKSPACE}/.cd/start.json<<EOF
{
  "apps" : {
    "name"        : "user-preference-api",
    "script"      : "build/server.js",
    "node_args"   : ["-r","dotenv/config"],
    "watch"       : false,
    "exec_interpreter" : "node",
    "exec_mode"        : "fork",
    "error_file"  : "/data/logs/user-preference-api/err.log",
    "out_file"    : "/data/logs/user-preference-api/out.log",
    "merge_logs"  : true,
    "pid_file"    : "/data/logs/user-preference-api/app.pid"
  }
}
EOF
